name: Assign PR Reviewers
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/reviewer-config.yml'