version: '3.8'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb2:/var/lib/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=adminuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=fasttrading
      - DOCKER_INFLUXDB_INIT_BUCKET=fasttrading
      
